### ISSUE TITLE
Fechamento do servidor instantâneo

### ISSUE THREAD

**Issue by Zhawty** [DripCodeScripts/drip_notify#1]
https://github.com/DripCodeScripts/drip_notify/blob/f4cb6313d5f52dc1a7667e2017a153073608d2a9/server.lua#L57

Creio que o correto seria colocar o "os.exit()" depois do for pois na primeira repetição ele ja ira encerrar o processo assim não expulsando os outros jogadores com as mensagens, somente o primeiro jogador, e para servidores que possuem sistema de cache por exiting traria rollback por falta de save de informações do player

**Comment by DripCodeScripts** [comment]
O erro do script estara sendo resolvido obrigado pelo report
